### ISSUE TITLE
Mac OSX intel version too low

### ISSUE THREAD

**Issue by matejsp** [scipy/oldest-supported-numpy#77]
Due to a bug:
https://github.com/numpy/numpy/issues/17987

It is not possible to build numpy on intel on version lower than 1.20.
I propose dropping arm requirement for darwin and let 1.21 for both ... intel and m1. 

```
            creating build

            creating build/src.macosx-13-x86_64-3.8

            creating build/src.macosx-13-x86_64-3.8/numpy

            creating build/src.macosx-13-x86_64-3.8/numpy/distutils

            building library "npymath" sources

            get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'

            customize Gnu95FCompiler

            Found executable /usr/local/bin/gfortran

            Traceback (most recent call last):

              File "<string>", line 2, in <module>

              File "<pip-setuptools-caller>", line 34, in <module>

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/setup.py", line 443, in <module>

                setup_package()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/setup.py", line 435, in setup_package

                setup(**metadata)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/core.py", line 171, in setup

                return old_setup(**new_attr)

              File "/private/tmp/workspace/workspace/ment_arch_package-builder_master/python38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup

                return distutils.core.setup(**attrs)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup

                dist.run_commands()

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands

                self.run_command(cmd)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command

                cmd_obj.run()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/install.py", line 62, in run

                r = self.setuptools_run()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/install.py", line 36, in setuptools_run

                return distutils_install.run(self)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run

                self.run_command('build')

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command

                self.distribution.run_command(command)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command

                cmd_obj.run()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/build.py", line 47, in run

                old_build.run(self)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run

                self.run_command(cmd_name)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command

                self.distribution.run_command(command)

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command

                cmd_obj.run()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/build_src.py", line 142, in run

                self.build_sources()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/build_src.py", line 153, in build_sources

                self.build_library_sources(*libname_info)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/build_src.py", line 286, in build_library_sources

                sources = self.generate_sources(sources, (lib_name, build_info))

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/build_src.py", line 369, in generate_sources

                source = func(extension, build_dir)

              File "numpy/core/setup.py", line 667, in get_mathlib_info

                st = config_cmd.try_link('int main(void) { return 0;}')

              File "/usr/local/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/config.py", line 241, in try_link

                self._check_compiler()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/command/config.py", line 82, in _check_compiler

                self.fcompiler = new_fcompiler(compiler=self.fcompiler,

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/__init__.py", line 884, in new_fcompiler

                compiler = get_default_fcompiler(plat, requiref90=requiref90,

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/__init__.py", line 855, in get_default_fcompiler

                compiler_type =  _find_existing_fcompiler(matching_compiler_types,

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/__init__.py", line 806, in _find_existing_fcompiler

                c.customize(dist)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/__init__.py", line 530, in customize

                linker_so_flags = self.flag_vars.linker_so

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__

                return self._get_var(name, conf_desc)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/environment.py", line 56, in _get_var

                var = self._hook_handler(name, hook)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook

                return hook()

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/gnu.py", line 353, in get_flags_linker_so

                flags = GnuFCompiler.get_flags_linker_so(self)

              File "/private/var/folders/7_/f4wxph953b18c_63q9qxlw5r0000gp/T/pip-install-smotc_bu/numpy_75a2c57acb7d4baeb98d20a46a455e95/numpy/distutils/fcompiler/gnu.py", line 144, in get_flags_linker_so

                os.environ['MACOSX_DEPLOYMENT_TARGET'] = target

              File "/usr/local/bin/../Cellar/python@3.8/3.8.17_1/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 680, in __setitem__

                value = self.encodevalue(value)

              File "/usr/local/bin/../Cellar/python@3.8/3.8.17_1/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 750, in encode

                raise TypeError("str expected, not %s" % type(value).__name__)

            TypeError: str expected, not int

            [end of output]
```

**Comment by rgommers** [comment]
I'm going to need some more info about your actual problem @matejsp. Folks have been using this package for several years now without issues. Can you please explain what exactly is breaking for you? 

`macosx-13` suggests that you may be forgetting to set `MACOSX_DEPLOYMENT_TARGET` or some such thing. 

Also, you can now migrate away from this package and build against numpy 1.25.x instead (it exports an older C API, see the note at https://numpy.org/devdocs/dev/depending_on_numpy.html#build-time-dependency).

**Comment by matejsp** [comment]
I want to build pandas and required numpy. Our company policy does not allow to use binaries, but we need to compile packages ourselves (so we can fork and patch if needed). 

Anyway ... running pip wheel on numpy==1.17.3 or pandas 2.0.3 (using latest oldest-supported-numpy -  https://github.com/pandas-dev/pandas/blob/v2.0.3/pyproject.toml) is failing because of invalid default mac version target on some systems.

From what I understand everytime Apple releases new major OS version:
```
python -m sysconfig | grep MACOSX_DEPLOYMENT_TARGET
```

results in:
MACOSX_DEPLOYMENT_TARGET = "13.2"
or 
MACOSX_DEPLOYMENT_TARGET = 13

So when you build on 13 ... you get a number instead of a string and this breaks compilation.

Another issue explaining why this is broken on some OS versions:
https://github.com/numpy/numpy/issues/18093 

I will try setting MACOSX_DEPLOYMENT_TARGET if this will help.

**Comment by matejsp** [comment]
I tried with:
export MACOSX_DEPLOYMENT_TARGET=10.13 and/or
export SYSTEM_VERSION_COMPAT=1

but not a single combination works ... this happens on python 3.8 (that we need) ... python 3.9 seems to build successfully

One or another:
```
    File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-14nynqkq/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 48, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-14nynqkq/overlay/lib/python3.8/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
```

when using both:
```
        error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "12.0" but "13" during configure
        [end of output]
```

Based on https://endoflife.date/numpy it is hard to target anything older than 1.22 since it is no longer supported.

**Comment by rgommers** [comment]
> Based on https://endoflife.date/numpy it is hard to target anything older than 1.22 since it is no longer supported.

That's security support date that someone arbitrarily put at 2 years. That's wrong, but either way it's not really relevant for a build-time-only requirement.

> `assert len(base_version) == 2`

I have no idea what is going on there, looks like a bug in `wheel`. 

I have a macOS arm64 machine with macOS 13.3. I can run `pip install numpy==1.17.3 --no-binary numpy` and it installs from source just fine. 

Do you have a standalone reproducer?

**Comment by matejsp** [comment]
One idea for this project future and easier usage/upgrades would be to replace all versions (that are 1.19.x & >=py3.9)

```
numpy==1.23.3,>=1.25.0<2; python_version=='3.9' and platform_system=='OS400' and platform_machine!='loongarch64'
```

ALTERNATIVE: I don't know if you can have multiple ranges that work with setup tools (maybe >= and then exclude all version up to 1.25.*:
```
numpy>=1.23.3,!=1.24.*,<2; 
or
numpy>=1.19.3,!=1.20.*,!=1.21.*,!=1.22.*,!=1.23.*,!=1.24.*,<2 ; python_version=='3.9' and platform_system not in 'OS400' and platform_machine not in 'arm64|loongarch64'
```

For most platforms you would then just pick best numpy version with best OS compatibility and STILL retain backwards compatibility :) Could be win win :D

**Comment by rgommers** [comment]
The 1.19/1.20 build issues due to dependencies are a class of problems that can't really be fixed in this package, since we must target the oldest version that works / has wheels (module the 1.25 and up changes). There's always a workaround though, by turning off build isolation and installing your desired `numpy` version in the environment before building the next packages that depend on numpy.

> One idea for this project future and easier usage/upgrades would be to replace all versions (that are 1.19.x & >=py3.9)
> ...
> For most platforms you would then just pick best numpy version with best OS compatibility and STILL retain backwards compatibility

This is a good idea in principle though, and while it's a major change I think we should adopt some version of this. It's related to gh-76, I'll copy your comment there since it's a generic improvement rather than being specific to the macOS Intel on Python 3.8 issue.
